version: 1
disable_existing_loggers: no

formatters:
  access_color:
    "()": uvicorn.logging.AccessFormatter
    fmt: '%(levelprefix)s %(asctime)s "%(request_line)s" %(status_code)s'
    use_colors: True
  access_file:
    "()": uvicorn.logging.AccessFormatter
    fmt: '%(levelprefix)s %(asctime)s "%(request_line)s" %(status_code)s'
    use_colors: False
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: '%Y-%m-%d %H:%M:%S'
  error:
    format: "%(asctime)s - %(name)s - %(levelname)s %(name)s.%(funcName)s: %(message)s"
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    level: DEBUG
    stream: ext://sys.stdout
  access_console:
    formatter: access_color
    class: logging.StreamHandler
    stream: "ext://sys.stdout"
  access_file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: access_file
    level: INFO
    filename: logs/access.log
    when: 'midnight'
    backupCount: 7
  error_file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: error
    level: ERROR
    filename: logs/error.log
    when: 'midnight'
    backupCount: 7

  
loggers:
  root:
    handlers: [console]
  ccbot:
    handlers: [console, error_file]
    level: DEBUG
    propagate: False
  uvicorn.access:
    handlers: [access_console, access_file]
    level: INFO
    propagate: False